apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: flux-system
type: Opaque
data:
  tunnel-token: eyJhIjoiZjcxNGNmNzc1NjNmZjE5NzM3ZmJiZjI3NDI1NDJiYjciLCJ0IjoiZmJiOGQ3YWEtZTVlYi00NGM1LWJiZmUtNzIwNWI2NzBjYTU5IiwicyI6IllUWXpNamMyWW1VdE56UmxZUzAwWkdNMUxUa3laVEF0TURJNU5XUmtaR1JrTWpNMCJ9
