{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysql-db-pass",
    "namespace": "flux-system",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mysql-db-pass",
        "namespace": "flux-system",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "password": "AgAm1xOGyR5nGs7hL0RAyze1NBh4g/qpCW7hy1VRZi+umAr3FToDhopspQ/7eXY1QhoMjWLI5mEEmM5vIy829USQP2cIvvl9vIWm1AQxzlxyg0ApXT/rzetyPcD2/ZaxqrI2LMm0jV/VHeQ3vCn7DptHGME4MQLktIKLOgxL0XYrBL95j8MO93cJ2jJhnrq0IpffAfy2mXnsLj6hFFm200n5irqs1wm9N3ocO+CXP9Hik2HO2Ip4SnGuJ+fjxjdITllkT1WzEHK/O8DmiOYJXN7x+VxHkRIo/vHSY0W1he+FU2Gk2RpblC4Rc1K4SYEBy1O6Dw8Tg6gEwH5klxja4Fwlt0b/Y2h+nx3XHe/rdODoWwt+TCtfDawgovWosxG8RyVxDioBFvNf4gb6SWkRg6P3xl2PRQ4fQe5j6tQJhUA9BzYxd4GPINo1U1GI1g5+81/jhM/AU+39HJzWEvK6fJjISJ7kGZtyyhqvyIMqZOXVBJoSRs6GZNwSxXnYkQvO/n2PRqczmJSn9TfTVe2QW+4qJeidBaQYcQul7oxdDpZQpYucUQdh/NjRvDX6maIvE7EuKnck363jWBoZ7g8v6josF0WtyW3tlDshH9DhPXMjIDh/buLVRPV7IXwjyNb2Ytul5KSYTngeDA8vxsySNpcVjfDzHgCV8d/uf9SK1o1wOPqvK1M2lMWF750g8GM40QhEsLFnm8PGfg=="
    }
  }
}
