apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate # Important for databases: don't start a new one until the old one stops
    
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
