apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-db-pass
  namespace: default
spec:
  encryptedData:
    password: AgAnbni/pOYRrCRMdFc1rlHFm7NfEgFW26/AckOJgbpLp9pUJ9k7fJ0DqADJXl7TxpbN7Y7+5VM7OZV/HGiebZBy1D5zq0SOdhvHn+EHH/2zpvnNPnbadCT1CMRsgTlRGth7wkN5DKlI1NrhE/HoU+B2W3+qTzX2NRsvhV1eoCKUjMB986SZcMFDAHv+2IvxfeI3Nr2BkN9UTiocZuijFJDR+9ro+AU50KI08VJ3PxrtQHUHz8wYLpLVbzEd6GqewAyC1sRfCY8aOxffdXrDf58rO0Zwj8E5NEXvGdXmtxBqTsrliLl+wyFVmu5py7xpdmY2l0fmCJI5iyEyMWgIp9jDQZRe0m8jTz0+ZyNBTXkEtrR+F+KtWduhh3H1NKU6x66R5MLRAHa1sdIg7Gq/MzeKgniCbmUoDtvmXf+Dcu1wsh2CK5idzUNVbwbYrsIlzUlpS5jIOG0GjgreQ/Yx1iJ1KDLOOkYJFnv2fcfFthqvwQHLLdsktgVT/35SA0zG8TgIgyfpiV2LtbBjrdGbV2d54c8Tu+1/2i/r+EFE/9bhhaFzIpRQoF4Xwt7HfvcJzfIOzq6/gVCefqa8+qUbpcHRQ8Pkucfz1kPxKM7MobNe4LzfJLOCDr4tBiH73bx418OCneC+VdYGCkHTieNA3tq4gAAWkRScLknxr+QU39H0qDfe0pNNXJaRthvwi8Mni4f6YWPlNVct1g==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-db-pass
      namespace: default

