apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-db-pass
  namespace: flux-system
spec:
  encryptedData:
    password: AgCimaNQht1GgiB72SbiJ5G3RzdGBkZ5SVnuyki6wgLulJ4XRrQTCZTjSMMJyUN/qQH1n8JsusOFNrzGV0A10Ql3HSmgxJnIOsHVFfgyg2cf3cfWsrAmBFiSBmJ/0gXtdnnNEZk5sH+EtN82cMmImcrDri+2Hro5ngN7OAQ/IL0TAgUS2hE2Y1Kv45dNxyircbobd7f7LakbS7CdZy+tJHLeJXwq8xSBmEPk+P9ARvJ8cZcfrPrasiHjK9h09VtxUVTwqaBrOVnFaQ9zV/VZ/qfULQTkivlL7L+Hm+vUsCSLEz1X6oBeNKf7zHXJzadQLiwnKmMEPK0XGW352g/02X9bdqvey1nTEMyNw3h+Fipqt8G1dwm+7zyjfEgtG8BCXVhSM2hn8O8v2Eeki5o6bGxpEct66jPUi6gESaHmeuSXM0+sKt8ylF+rJvesWRAvwvxXVqYYRNP2sdGZJGYxcFzCxoRzQK3fVoY+UDaF8/n7SGO3K+T0rIHBvOGQu2yIPvi7toiwhxtPSPBqhzg8Iaoc9OW9rH70HY96gTaC3ahPgyLMrb6z+T/QhByeuRvAz26EeWfH1acLNMYo7QqLbnrBzfeLfFaubHA/+nPAzDWeVJ8peoThz5MkLZx4cdG7yyVU7YUdMI1otv11eH6/6W6+jmQPRGZQ49HdXMDfp2PblSjAL0ffHYYKUSq89//dFGzmUS2xCETB3A==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-db-pass
      namespace: flux-system

