apiVersion: v1
data:
  token: ZXlKaElqb2laamN4TkdObU56YzFOak5tWmpFNU56TTNabUppWmpJM05ESTFOREppWWpjaUxDSjBJam9pTjJNeVpESmtNRE10TkRoa1lTMDBNemhtTFdGa01tTXRZekkxWkdVM01USTFNamt3SWl3aWN5STZJazFFWkd0WmFtYzBUbnBCZEU1WFNUTk9RekF3VFVSb2JFeFViR2xOUjAxMFdsUkZNMWxVVFhsTlJFRjVUMFJqTlNKOQ==
kind: Secret
metadata:
  name: tunnel-token
  namespace: flux-system
