apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token  # Must match your cloudflare-tunnel.yaml
  namespace: flux-system
type: Opaque
data:
  token: ZXlKaElqb2laamN4TkdObU56YzFOak5tWmpFNU56TTNabUppWmpJM05ESTFOREppWWpjaUxDSjBJam9pWm1KaU9HUTNZV0V0WlRWbFlpMDBOR00xTFdKaVptVXROekl3TldJMk56QmpZVFU1SWl3aWN5STZJbGxVV1hwTmFtTXlXVzFWZEU1NlVteFpVekF3V2tkTk1VeFVhM2xhVkVGMFRVUkpOVTVYVW10YVIxSnJUV3BOTUNKOQ==
